# Generated by Django 2.2.12 on 2022-04-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VAL',
            fields=[
                ('NumOF', models.IntegerField(primary_key=True, serialize=False)),
                ('NumV', models.IntegerField()),
                ('valide', models.IntegerField()),
                ('date1', models.CharField(default='', max_length=100)),
                ('date2', models.CharField(default='', max_length=100)),
                ('date3', models.CharField(default='', max_length=100)),
                ('date4', models.CharField(default='', max_length=100)),
                ('date5', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
