# Generated by Django 2.2.12 on 2022-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='val',
            name='pri',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
