# Generated by Django 2.2.12 on 2022-05-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_val_pri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='val',
            name='pri',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
