# Generated by Django 2.2.12 on 2022-06-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_auto_20220530_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='val',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
