# Generated by Django 2.2.12 on 2022-04-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LIST_PIECES',
            fields=[
                ('id_piéce', models.AutoField(primary_key=True, serialize=False)),
                ('NumOF', models.IntegerField()),
                ('Qte', models.CharField(max_length=100)),
                ('Désignation', models.CharField(max_length=100)),
                ('Matiére', models.CharField(max_length=100)),
                ('Dimension', models.CharField(max_length=100)),
                ('Qual', models.CharField(max_length=100)),
                ('Prévu_h', models.CharField(max_length=100)),
                ('Réalisé_h', models.CharField(max_length=100)),
                ('Conformité_C', models.CharField(max_length=100)),
                ('Conformité_NC', models.CharField(max_length=100)),
            ],
        ),
    ]
