# Generated by Django 2.2.12 on 2022-04-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListPieces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_pieces',
            name='Conformité_C',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Conformité_NC',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Dimension',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Désignation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Matiére',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Prévu_h',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Qte',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Qual',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Réalisé_h',
            field=models.CharField(default='', max_length=100),
        ),
    ]
