# Generated by Django 2.2.12 on 2022-05-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListPieces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_pieces',
            name='Conf_C',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Conf_NC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='NConf_C',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='NConf_NC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Rest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
