# Generated by Django 2.2.12 on 2022-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListPieces', '0002_auto_20220517_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_pieces',
            name='avancement',
            field=models.CharField(default='..', max_length=100),
        ),
    ]
