# Generated by Django 2.2.12 on 2022-06-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListPieces', '0003_list_pieces_avancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_pieces',
            name='id_plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list_pieces',
            name='lien',
            field=models.CharField(default='..', max_length=300),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='statut',
            field=models.CharField(default='Ready', max_length=100),
        ),
    ]
