# Generated by Django 2.2.12 on 2022-05-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OF',
            fields=[
                ('NumOF', models.IntegerField(primary_key=True, serialize=False)),
                ('NomPr', models.CharField(default='..', max_length=100)),
                ('StatutPr', models.CharField(default='..', max_length=100)),
                ('RefPr', models.IntegerField(blank=True, null=True)),
                ('Priorité', models.CharField(default='..', max_length=100)),
                ('Realise_T', models.IntegerField(blank=True, null=True)),
                ('Rest_T', models.IntegerField(blank=True, null=True)),
                ('Avancement', models.CharField(default='..', max_length=100)),
                ('State', models.CharField(default='..', max_length=100)),
            ],
        ),
    ]
