# Generated by Django 2.2.12 on 2022-05-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followUP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='of',
            name='cloture',
            field=models.CharField(default='..', max_length=100),
        ),
    ]
