# Generated by Django 2.2.12 on 2022-04-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followUP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='of',
            name='NomPr',
            field=models.CharField(default='..', max_length=100),
        ),
        migrations.AlterField(
            model_name='of',
            name='Priorité',
            field=models.CharField(default='..', max_length=100),
        ),
        migrations.AlterField(
            model_name='of',
            name='StatutPr',
            field=models.CharField(default='..', max_length=100),
        ),
    ]
